/**
 * Every firm setting with its default. Settings are rows in `Setting`; a missing row means
 * the default applies. Statutory values are NOT here — they live in effective-dated tables.
 */
export const SETTING_DEFAULTS = {
  "session.idleMinutes": { value: 30, description: "Log out after this many idle minutes" },
  "session.absoluteHours": { value: 12, description: "Log out after this many hours regardless of activity" },
  "login.maxFailures": { value: 5, description: "Failed logins before the account is locked" },
  "login.lockMinutes": { value: 15, description: "Minutes an account stays locked" },
  "work.dailySoftWarnMinutes": { value: 720, description: "Soft warning when a day's total crosses this (spec 5.3)" },
  "work.weeklyLockTime": { value: "16:00", description: "Weekly lock time on Sunday (IST) — Q-12" },
  "work.workingSaturdays": { value: true, description: "Saturdays are working days" },
  "upload.maxMegabytes": { value: 25, description: "Largest allowed upload" },
  "portal.inviteDays": { value: 7, description: "Days a portal invite link stays valid" },
  "portal.totpMandatory": { value: false, description: "Require TOTP for portal users (open-questions Q-07)" },
  "backup.keepAuto": { value: 14, description: "Automatic backups to keep" },
  "backup.nightlyTime": { value: "23:30", description: "Time of the nightly automatic backup (IST)" },
  "eqr.feeThresholdPaise": { value: 50_000_00, description: "Audit fee at or above which EQR is required" },
  "budget.bands": { value: [85, 100, 110], description: "Budget band thresholds in % (spec 5.3)" },
  "compliance.trackingFrom": { value: "2026-04-01", description: "Compliance tasks are generated from this date (no older periods are created)" },
  "compliance.agmCeilingMonths": { value: 6, description: "AGM deadline used for provisional dates: months after FY end (Q-10)" },
  "compliance.firstAgmCeilingMonths": { value: 9, description: "First AGM deadline: months after the first FY end (Q-10)" },
  "compliance.createDueFrom": { value: "", description: "Go-live cut-off (YYYY-MM-DD): tasks due before this date are not created, because that work was done before the app was used. Blank = create everything from the tracking date (Q-32)" },
  "notice.defaultResponseDays": { value: 15, description: "Notice response due = received + days, when the notice gives no date (Q-13)" },
  "udin.awaitingDays": { value: 7, description: "Signed document shows 'Awaiting UDIN' after this many days" },
  "dsc.expiryAlertDays": { value: [30, 7], description: "DSC expiry alerts (days before expiry)" },
  "credentials.changeAfterDays": { value: 90, description: "Flag 'change periodically' credentials older than this" },
  "work.missingEntryLookbackDays": { value: 14, description: "Days checked for missing work entries" },
  "reminders.upcomingDays": { value: [7, 3, 1], description: "Due-date reminders: days before the due date (Rules Spec 9)" },
  "reminders.managerEscalationDays": { value: 1, description: "Overdue by this many days → escalate to the Manager" },
  "reminders.partnerEscalationDays": { value: 3, description: "Overdue by this many days → escalate to the Partner" },
  "reminders.pendingFollowUpEveryDays": { value: 3, description: "Pending from client: remind the assignee to follow up every N days" },
  "reminders.pendingEscalationDays": { value: 10, description: "Pending from client this long with the due date near → escalate to the Manager" },
  "reminders.pendingEscalationDueWithinDays": { value: 5, description: "…when the due date is within this many days" },
  "reminders.reviewSlaDays": { value: 2, description: "Review waiting this long → remind the checker (twice as long → Partner)" },
  // Phase 3 — billing (Q-18). GST rate and SAC codes confirmed by the firm (Q-35); revisit if GST law changes.
  "billing.gstRateBp": { value: 1800, description: "GST rate on professional fees, in basis points (1800 = 18%; confirmed Q-35)" },
  "billing.sacByServiceLine": { value: { ACCOUNTING: "998222", AUDIT: "998221", DIRECT_TAX: "998231", GST: "998231", COMPANY_LAW: "998216", ADVISORY: "998311" }, description: "SAC code per service line (confirmed Q-35)" },
  "billing.defaultSac": { value: "998231", description: "SAC when the service line is not mapped (confirmed Q-35)" },
  "billing.invoicePrefix": { value: "QI", description: "Invoice series code; numbers are <code>/yy-yy/0001 (≤16 characters, Q-18)" },
  "billing.paymentTermsDays": { value: 15, description: "Invoice due date = invoice date + days" },
  "billing.unbilledAlertDays": { value: 30, description: "Flag unbilled chargeable work older than this" },
  "billing.reminderDays": { value: [15, 30, 60], description: "Payment reminder points (days since invoice, overdue invoices only)" },
  "billing.retainerMonthlyDivisor": { value: 12, description: "Monthly retainer draft = engagement fee ÷ this" },
  "billing.retainerDraftDay": { value: 1, description: "Day of the month from which retainer drafts are created" },
  // Phase 3 — CRM
  "crm.proposalApprovalLimitPaise": { value: 0, description: "Managers may approve proposals up to this fee (0 = Partner only)" },
  "crm.proposalValidityDays": { value: 30, description: "Default proposal validity" },
  "crm.renewalLeadDays": { value: 60, description: "Renewal prompt this many days before the new period (spec 10.7)" },
  "crm.renewalTargetMarkupPct": { value: 50, description: "Renewal fee suggestion is at least last period's cost plus this %" },
  "crm.renewalMinIncreasePct": { value: 0, description: "Renewal fee suggestion is at least last fee plus this %" },
  "crm.feedbackLowScore": { value: 2, description: "Client ratings at or below this alert the Partner" },
  "crm.feedbackLookbackDays": { value: 30, description: "Feedback requests for engagements closed within this many days" },
  // Phase 3 — HR processes
  "articleship.extendByExcessLeave": { value: true, description: "Excess articleship leave extends the completion date day for day" },
  "articleship.completionAlertDays": { value: 90, description: "Flag articles completing within this many days" },
  "articleship.countedLeaveTypes": { value: ["PERSONAL", "SICK", "EXAM_STUDY", "OTHER"], description: "Leave types counted against the articleship entitlement" },
  "cpe.memberClass": { value: "PRACTICE", description: "CPE requirement class that applies to the firm's members" },
  "cpe.shortfallAlertDays": { value: 90, description: "Warn about a CPE shortfall this many days before the year/block end" },
  "expenses.conveyanceLookbackDays": { value: 30, description: "Days of Client Site entries offered as conveyance suggestions" },
  "exit.noticeDaysByRole": { value: { PARTNER: 90, MANAGER: 60, STAFF: 30, ARTICLE: 30, PRACTICE_ADMIN: 30, HR_ADMIN: 30 }, description: "Default notice period by role (firm policy)" },
  "exit.recoverNoticeShortfall": { value: true, description: "Recover unserved notice days in full-and-final" },
  // Phase 3 — payroll (Q-09). Statutory rates are in the effective-dated rate tables, not here.
  "payroll.daysBasis": { value: "CALENDAR", description: "Days a month is paid on: CALENDAR, FIXED_30 or FIXED_26" },
  "payroll.pfWageBasis": { value: "CAPPED", description: "PF on basic capped at the wage ceiling, or FULL basic (Q-09c)" },
  "payroll.defaultRegime": { value: "NEW", description: "Default income-tax regime on new salary structures" },
  "payroll.esiRoundUpToRupee": { value: true, description: "Round each ESI share up to the next rupee" },
  "payroll.stipendLocationClass": { value: "POP_20L_PLUS", description: "Firm's city class for the minimum article stipend (Jaipur: over 20 lakh population)" },
  "payroll.form16Label": { value: "Form 16", description: "Label of the annual salary TDS certificate (Form 16, confirmed Q-34)" },
  // Phase 3 — documents, QC, collaboration
  "qc.inspectionSampleSize": { value: 5, description: "Engagements sampled at random for a periodic file inspection" },
  "comments.editWindowMinutes": { value: 15, description: "Minutes an author can edit their own comment" },
  "helpdesk.longOpenDays": { value: 7, description: "Open or in-progress tickets older than this are flagged" },
} as const;

export type SettingKey = keyof typeof SETTING_DEFAULTS;
