import { db, type Tx } from "../../lib/db";
import { todayIst } from "../../lib/dates";
import { writeAudit } from "../../audit";
import { systemActor, type Actor } from "../../permissions/actor";
import {
  obligationsFor, planGeneration, planObligationEnds, planEventRecompute, naturalKey,
  type ExistingTask, type TaskCreate, type TaskUpdate, type TaskStatus,
} from "../../compliance-engine";
import { loadMaster, type Master } from "./master";
import { buildSnapshot } from "./snapshot";
import { logger } from "../../lib/logger";
import { nextCode } from "../../lib/codes";

export type SyncResult = { created: number; closed: number; recomputed: number };

/** Engagement names hint which recurring engagement a type belongs to when a client has several of one kind. */
const ENGAGEMENT_HINTS: Record<string, RegExp> = {
  TAR: /tax audit/i, "TP-3CEB": /3ceb|transfer/i, "STAT-AUDIT": /statutory/i,
};

async function engagementFor(tx: Tx, master: Master, clientId: string, typeCode: string, cache: Map<string, string>) {
  const type = master.types.get(typeCode)!;
  const family = master.families.get(type.familyCode);
  const engagementType = family?.stageTemplateCode ?? "OTHER";
  const cacheKey = `${engagementType}|${ENGAGEMENT_HINTS[typeCode] ? typeCode : ""}`;
  const hit = cache.get(cacheKey);
  if (hit) return hit;
  const candidates = await tx.engagement.findMany({
    where: { clientId, recurrence: "RECURRING", status: "ACTIVE", engagementType },
    orderBy: { createdAt: "asc" },
  });
  const hint = ENGAGEMENT_HINTS[typeCode];
  let eng = candidates.find((e) => e.complianceTypeCode === typeCode) ?? (hint ? candidates.find((e) => hint.test(e.name)) : undefined) ?? candidates.find((e) => !Object.values(ENGAGEMENT_HINTS).some((h) => h.test(e.name))) ?? candidates[0];
  if (!eng) {
    // The calendar creates the recurring engagement when none exists (Product Spec 4.2).
    const client = await tx.client.findUniqueOrThrow({ where: { id: clientId } });
    const version = await tx.stageTemplateVersion.findFirst({ where: { template: { code: engagementType }, status: "ACTIVE" }, orderBy: { version: "desc" } });
    eng = await tx.engagement.create({
      data: {
        code: await nextCode(tx, "engagement"),
        clientId, name: `${family?.name ?? type.name} (recurring)`, serviceLine: type.serviceLine, engagementType, recurrence: "RECURRING",
        stageTemplateVersionId: version?.id ?? null, partnerId: client.partnerId, managerId: client.managerId, startDate: todayIst(), createdById: "system",
      },
    });
  }
  cache.set(cacheKey, eng.id);
  return eng.id;
}

async function createTask(tx: Tx, master: Master, t: TaskCreate, engCache: Map<string, string>, today: string) {
  const type = master.types.get(t.typeCode)!;
  const family = master.families.get(type.familyCode);
  const engagementId = await engagementFor(tx, master, t.clientId, t.typeCode, engCache);
  const engagement = await tx.engagement.findUniqueOrThrow({ where: { id: engagementId }, include: { assignments: { where: { toDate: null } } } });
  const versionId = engagement.stageTemplateVersionId ?? (await tx.stageTemplateVersion.findFirst({ where: { template: { code: family?.stageTemplateCode ?? "OTHER" }, status: "ACTIVE" } }))?.id ?? null;
  const task = await tx.task.create({
    data: {
      clientId: t.clientId, engagementId, complianceTypeCode: t.typeCode, partyKey: t.partyKey, periodKey: t.periodKey, periodLabel: t.periodLabel,
      periodStart: t.periodStart, periodEnd: t.periodEnd, title: t.title, originalDueDate: t.dueDate, effectiveDueDate: t.dueDate, isProvisional: t.isProvisional,
      dueBasis: t.dueBasis, holidayShifted: t.holidayShifted, gstinId: t.gstinId ?? null, directorId: t.directorId ?? null, stageTemplateVersionId: versionId,
      ackType: type.ackType, createdById: "system",
    },
  });
  const maker = engagement.assignments.find((a) => a.role === "MAKER") ?? engagement.assignments.find((a) => a.role === "MEMBER");
  const rows = [
    ...(maker ? [{ userId: maker.userId, role: "ASSIGNEE" }, { userId: maker.userId, role: "MAKER" }] : []),
    ...engagement.assignments.filter((a) => a.role === "CHECKER" || a.role === "EQR").map((a) => ({ userId: a.userId, role: a.role })),
  ];
  for (const r of rows) await tx.taskAssignment.create({ data: { taskId: task.id, userId: r.userId, role: r.role, fromDate: today, createdById: "system" } });
  await tx.taskStatusHistory.create({ data: { taskId: task.id, fromStatus: null, toStatus: "UPCOMING", reason: "Generated by the compliance calendar", createdById: "system" } });
  if (t.dueDate) await tx.dueDateHistory.create({ data: { taskId: task.id, oldValue: null, newValue: t.dueDate, source: t.holidayShifted ? "HOLIDAY_SHIFT" : "GENERATION", reference: t.dueBasis, createdById: "system" } });
  if (family?.checklistTemplateCode) {
    const tpl = await tx.checklistTemplate.findUnique({ where: { code: family.checklistTemplateCode }, include: { items: { orderBy: { sortOrder: "asc" } } } });
    for (const it of tpl?.items ?? []) {
      await tx.checklistItem.create({ data: { clientId: t.clientId, engagementId, taskId: task.id, label: it.label, sortOrder: it.sortOrder, keywords: it.keywords, createdById: "system" } });
    }
  }
  return task;
}

/** Apply engine updates (status / dates) with history and audit entries. */
export async function applyUpdates(tx: Tx, actor: Actor, updates: TaskUpdate[], current: Map<string, ExistingTask>) {
  for (const u of updates) {
    const before = current.get(u.taskId)!;
    const data: Record<string, unknown> = {};
    if (u.status) data.status = u.status;
    if (u.status === "NOT_APPLICABLE") data.notApplicableReason = u.notApplicableReason ?? u.statusReason;
    if (u.effectiveDueDate !== undefined) data.effectiveDueDate = u.effectiveDueDate;
    if (u.originalDueDate !== undefined) data.originalDueDate = u.originalDueDate;
    if (u.isProvisional !== undefined) data.isProvisional = u.isProvisional;
    await tx.task.update({ where: { id: u.taskId }, data });
    if (u.status && u.status !== before.status) {
      await tx.taskStatusHistory.create({ data: { taskId: u.taskId, fromStatus: before.status, toStatus: u.status, reason: u.statusReason ?? "", createdById: actor.kind === "PORTAL" ? null : actor.userId } });
    }
    if (u.history) {
      await tx.dueDateHistory.create({ data: { taskId: u.taskId, oldValue: u.history.oldValue, newValue: u.history.newValue ?? "", source: u.history.source, reference: u.history.reference, createdById: actor.kind === "PORTAL" ? null : actor.userId } });
    }
    await writeAudit(tx, actor, {
      entityType: "Task", entityId: u.taskId, action: u.status ? "STATUS" : "DUE_DATE",
      before: { status: before.status, effectiveDueDate: before.effectiveDueDate, isProvisional: before.isProvisional },
      after: { status: u.status ?? before.status, effectiveDueDate: u.effectiveDueDate ?? before.effectiveDueDate, isProvisional: u.isProvisional ?? before.isProvisional },
      reason: u.statusReason ?? u.history?.reference ?? "",
    });
  }
}

export function toExisting(t: { id: string; clientId: string; complianceTypeCode: string | null; partyKey: string; periodKey: string; periodStart: string; status: string; originalDueDate: string | null; effectiveDueDate: string | null; isProvisional: boolean; filedDate: string | null }): ExistingTask {
  return {
    id: t.id, clientId: t.clientId, typeCode: t.complianceTypeCode ?? "", partyKey: t.partyKey, periodKey: t.periodKey, periodStart: t.periodStart,
    status: t.status as TaskStatus, originalDueDate: t.originalDueDate, effectiveDueDate: t.effectiveDueDate, isProvisional: t.isProvisional, filedDate: t.filedDate,
  };
}

/**
 * Bring one client's compliance tasks in line with its master data (Rules Spec 3, 4, 7):
 * close tasks that no longer apply, create missing periods up to the horizon, recompute event-linked
 * dates, and keep the subscription start/stop dates. Idempotent; runs nightly and on every client change.
 */
export async function syncClientCompliance(clientId: string, opts: { today?: string; actor?: Actor; master?: Master } = {}): Promise<SyncResult> {
  const today = opts.today ?? todayIst();
  const actor = opts.actor ?? systemActor();
  const master = opts.master ?? (await loadMaster());
  return db().$transaction(
    async (tx) => {
      const snapshot = await buildSnapshot(tx, clientId, master.trackingFrom, today);
      const obligations = obligationsFor(snapshot);

      // Subscriptions record the current window per (type, party) for display (compliance start date).
      for (const o of obligations) {
        await tx.clientComplianceSubscription.upsert({
          where: { clientId_complianceTypeCode_partyKey: { clientId, complianceTypeCode: o.typeCode, partyKey: o.partyKey } },
          create: { clientId, complianceTypeCode: o.typeCode, partyKey: o.partyKey, startDate: o.start, endDate: o.end ?? null, endReason: o.endReason ?? null, createdById: "system" },
          update: { startDate: o.start, endDate: o.end ?? null, endReason: o.endReason ?? null },
        });
      }

      const rows = await tx.task.findMany({ where: { clientId, complianceTypeCode: { not: null } } });
      const existing = rows.map(toExisting);
      const byId = new Map(existing.map((t) => [t.id, t]));

      const ends = planObligationEnds(existing, obligations, { suppressAutoNa: snapshot.status === "DISCONTINUED" || snapshot.status === "DISCONTINUED_CLOSED" });
      await applyUpdates(tx, actor, ends, byId);

      const gstins = await tx.gSTIN.findMany({ where: { clientId } });
      const directors = await tx.director.findMany({ where: { primaryClientId: clientId } });
      const states = await tx.state.findMany();
      const partyLabels = new Map<string, string>([
        ...gstins.map((g) => [g.id, g.gstin] as [string, string]),
        ...directors.map((d) => [d.id, `${d.name} (DIN ${d.din})`] as [string, string]),
        ...states.map((s) => [s.code, s.name] as [string, string]),
      ]);
      const creates = planGeneration({
        client: snapshot, obligations, types: master.types, rules: master.rules,
        existingKeys: new Set(existing.map((t) => naturalKey(t.typeCode, t.partyKey, t.periodKey))),
        today, holidays: master.holidays, stateGroups: master.stateGroups, gstinStates: new Map(gstins.map((g) => [g.id, g.stateCode])),
        partyLabels, agmCeilingMonths: master.agmCeilingMonths, firstAgmCeilingMonths: master.firstAgmCeilingMonths,
      });
      const engCache = new Map<string, string>();
      // Go-live cut-off (Q-32): obligations already due before the firm started using the app were handled
      // outside it, so they are not created. Tasks with no date yet (manual due dates) are still created.
      const dueFrom = master.createDueFrom;
      for (const t of creates) {
        if (dueFrom && t.dueDate && t.dueDate < dueFrom) continue;
        await createTask(tx, master, t, engCache, today);
      }

      // Link superseded tasks (GST frequency change) to the task that now covers their period.
      for (const u of ends.filter((x) => x.supersededByKey)) {
        const old = byId.get(u.taskId)!;
        const replacement = await tx.task.findFirst({
          where: { clientId, complianceTypeCode: u.supersededByKey!.typeCode, partyKey: old.partyKey, periodStart: { lte: old.periodStart }, periodEnd: { gte: old.periodStart } },
        });
        if (replacement) await tx.task.update({ where: { id: u.taskId }, data: { supersededByTaskId: replacement.id } });
      }

      const recompute = planEventRecompute(snapshot, existing.filter((t) => !ends.some((e) => e.taskId === t.id)), master.types, master.rules, master);
      await applyUpdates(tx, actor, recompute, byId);

      if (creates.length || ends.length || recompute.length) {
        await writeAudit(tx, actor, { entityType: "Client", entityId: clientId, action: "COMPLIANCE_SYNC", after: { created: creates.length, closed: ends.length, recomputed: recompute.length } });
      }
      return { created: creates.length, closed: ends.length, recomputed: recompute.length };
    },
    { timeout: 120_000, maxWait: 20_000 },
  );
}

/** Nightly job: every client that is not closed. */
export async function syncAllClients(today = todayIst()) {
  const master = await loadMaster();
  const clients = await db().client.findMany({ where: { status: { not: "DISCONTINUED_CLOSED" } }, select: { id: true } });
  const total: SyncResult = { created: 0, closed: 0, recomputed: 0 };
  for (const c of clients) {
    try {
      const r = await syncClientCompliance(c.id, { today, master });
      total.created += r.created;
      total.closed += r.closed;
      total.recomputed += r.recomputed;
    } catch (e) {
      logger().error({ clientId: c.id, err: e instanceof Error ? e.message : String(e) }, "compliance sync failed for client");
    }
  }
  return { clients: clients.length, ...total };
}
